export const TextureKeys = {
    ABANDONED_FLOOR: 'Abandoned-Floor.png',
    DESERT_FLOOR: 'Desert-Floor.png',
    MECHANIC_FLOOR: 'Mechanic-Floor.png',
    OBJECTS: 'Objects.png',
    SUMMIT_FLOOR: 'Summit-Floor.png',
    PROTAGONIST: 'protagonist',
    DOOR_SHEET: 'door-sheet',
    DOOR_SYMBOL: 'door-symbol',
    TRANSITION: 'transition',
    ACHIEVEMENT_UI: 'achievement-ui',
    BATTLE_UI: 'battle-ui',
    BOOK_UI: 'book-ui',
    BOOK_LAYOUT: 'book-layout',
    BOOK_LAYOUT_2: 'book-layout-2',
    BOOK_LAYOUT_3: 'book-layout-3',
    BOOK_LAYOUT_4: 'book-layout-4',
    BOOK_LAYOUT_5: 'book-layout-5',
    PLAYER_UI: 'player-ui',
    RUNE_OVERLAY: 'rune-overlay',
    CHAIN_LINK: 'chain-link',
    BOOKMARKS_UI: 'bookmarks-ui',
    GLOSSARY: 'glossary',
    ATTACK_SELECTOR: 'attack-selector',
    ITEMS: 'items',
    CURRENCY: 'currency',
    HOME_ANIM: 'homeAnim',
    SELECTOR_ANIM: 'selectorAnim',
    MULTIPLAYER_BG: 'multiplayer-bg',
    MULTIPLAYER_ROOM_UI: 'multiplayer-room-ui',
    MULTIPLAYER_ROOM_UI_2: 'multiplayer-room-ui-2',
    GO_BACK_UI: 'go-back-ui',
    UI_ITEMS: 'ui-items',
    MAP_OUTLINES: 'map-outlines',
    MAP_BOSS_OUTLINES: 'map-boss-outlines',
    MAP_CENTRAL_HUB: 'map-central-hub',
    MAP_TRADE_HUB: 'map-trade-hub',
    CULTIST: 'cultist',
    GOLEM: 'golem',
    RATIONALIST: 'rationalist',
    SCAVENGER: 'scavenger',
    SLIME: 'slime',
    WISP: 'wisp',
} as const;

export const MapKeys = {
    CENTRAL_HUB: 'central-hub',
    BOSS_ABANDONED: 'boss-floor-abandoned',
    BOSS_DESERT: 'boss-floor-desert',
    BOSS_MECHANIC: 'boss-floor-mechanic',
    SETTLEMENT_ABANDONED: 'abandoned-settlement',
    SETTLEMENT_DESERT: 'desert-settlement',
    SETTLEMENT_MECHANIC: 'mechanic-settlement',
    MERCHANT: 'merchant',
} as const;

export const AnimationKeys = {
    IDLE: 'idle',
    RUN: 'run',
    STOP: 'stop',
    DOOR_OPEN: 'door-open',
    CHAIN_ANIM: 'chain-anim',
    ATTACK_SELECTOR_ANIM: 'attack-selector-anim',
    SELECTOR_ANIM: 'sel_anim',
} as const;

export const FontKeys = {
    VCR: 'VCRosdNEUE',
    RUNE: 'RuneFont',
} as const;
